/*******************************************************************************
 * Copyright (c) 2009 VMware, Inc. licensed under the terms of the BSD. All
 * other rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * - Neither the name of VMware, Inc. nor the names of its contributors may be
 * used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

/* Auto-generated by VixHeaderToJava from the vix.h header file */
package com.vmware.vix;

@SuppressWarnings("serial")
public class VixError extends VixType {

   public static final VixError VIX_E_DISK_RAWTOOSMALL = new VixError(16029);
   public static final VixError VIX_E_UNRECOGNIZED_COMMAND_IN_GUEST = new VixError(3025);
   public static final VixError VIX_E_FILE_NAME_TOO_LONG = new VixError(20004);
   public static final VixError VIX_E_HOST_NETWORK_CONN_REFUSED = new VixError(14009);
   public static final VixError VIX_E_WRAPPER_SERVICEPROVIDER_NOT_FOUND = new VixError(22003);
   public static final VixError VIX_E_GUEST_VOLUMES_NOT_FROZEN = new VixError(20000);
   public static final VixError VIX_E_INVALID_HOSTNAME_SPECIFICATION = new VixError(18002);
   public static final VixError VIX_E_FILE_ALREADY_EXISTS = new VixError(12);
   public static final VixError VIX_E_TOOLS_INSTALL_DEVICE_NOT_CONNECTED = new VixError(21003);
   public static final VixError VIX_E_CRYPTO_NEED_PASSWORD = new VixError(17004);
   public static final VixError VIX_E_FILE_ERROR = new VixError(7);
   public static final VixError VIX_E_NOT_A_FILE = new VixError(20001);
   public static final VixError VIX_E_VMX_MSG_DIALOG_AND_NO_UI = new VixError(3028);
   public static final VixError VIX_E_UNRECOGNIZED_COMMAND = new VixError(3001);
   public static final VixError VIX_E_NEED_KEY = new VixError(30);
   public static final VixError VIX_E_GUEST_USER_PERMISSIONS = new VixError(3015);
   public static final VixError VIX_E_ROOT_GUEST_OPERATIONS_PROHIBITED = new VixError(3019);
   public static final VixError VIX_E_DISK_NOTENCDESC = new VixError(16020);
   public static final VixError VIX_E_NO_SUCH_PROCESS = new VixError(20003);
   public static final VixError VIX_E_NOT_A_DIRECTORY = new VixError(20002);
   public static final VixError VIX_E_OUT_OF_MEMORY = new VixError(2);
   public static final VixError VIX_E_CRYPTO_BAD_BUFFER_SIZE = new VixError(17001);
   public static final VixError VIX_E_TEMPLATE_VM = new VixError(4003);
   public static final VixError VIX_E_TOOLS_INSTALL_ALREADY_UP_TO_DATE = new VixError(21010);
   public static final VixError VIX_E_DISK_OUTOFRANGE = new VixError(16007);
   public static final VixError VIX_E_CRYPTO_BAD_FORMAT = new VixError(17009);
   public static final VixError VIX_E_TOOLS_NOT_RUNNING = new VixError(3016);
   public static final VixError VIX_E_CRYPTO_KEYSAFE_LOCATOR = new VixError(17012);
   public static final VixError VIX_E_FILE_NAME_INVALID = new VixError(22);
   public static final VixError VIX_E_HOST_USER_PERMISSIONS = new VixError(3014);
   public static final VixError VIX_E_DISK_NEEDVMFS = new VixError(16022);
   public static final VixError VIX_E_CANNOT_READ_VM_CONFIG = new VixError(4002);
   public static final VixError VIX_E_CANNOT_CONNECT_TO_VM = new VixError(3008);
   public static final VixError VIX_E_OPERATION_NOT_ALLOWED_FOR_LOGIN_TYPE = new VixError(3031);
   public static final VixError VIX_E_TIMEOUT_WAITING_FOR_TOOLS = new VixError(3000);
   public static final VixError VIX_E_DISK_PARTIALCHAIN = new VixError(16003);
   public static final VixError VIX_E_SNAPSHOT_NOTFOUND = new VixError(13003);
   public static final VixError VIX_E_SNAPSHOT_NONUNIQUE_NAME = new VixError(13017);
   public static final VixError VIX_E_LOGIN_TYPE_NOT_SUPPORTED = new VixError(3032);
   public static final VixError VIX_E_CANNOT_POWER_ON_VM = new VixError(3041);
   public static final VixError VIX_E_FILE_NOT_FOUND = new VixError(4);
   public static final VixError VIX_OK = new VixError(0);
   public static final VixError VIX_E_PROGRAM_NOT_STARTED = new VixError(3004);
   public static final VixError VIX_E_CRYPTO_NOT_IN_DICTIONARY = new VixError(17006);
   public static final VixError VIX_E_TOOLS_INSTALL_CANCELLED = new VixError(21004);
   public static final VixError VIX_E_DISK_INVALIDCHAIN = new VixError(16030);
   public static final VixError VIX_E_INVALID_HANDLE = new VixError(1000);
   public static final VixError VIX_E_INVALID_PROPERTY_VALUE = new VixError(6001);
   public static final VixError VIX_E_SCREEN_CAPTURE_BAD_FORMAT = new VixError(19001);
   public static final VixError VIX_E_TOOLS_INSTALL_ERROR = new VixError(21009);
   public static final VixError VIX_E_DISK_CANTSHRINK = new VixError(16009);
   public static final VixError VIX_E_CRYPTO_NO_CRYPTO = new VixError(17007);
   public static final VixError VIX_E_TYPE_MISMATCH = new VixError(2001);
   public static final VixError VIX_E_VM_ALREADY_UP_TO_DATE = new VixError(4006);
   public static final VixError VIX_E_DISK_UNSUPPORTEDDISKVERSION = new VixError(16011);
   public static final VixError VIX_E_DISK_NOINIT = new VixError(16001);
   public static final VixError VIX_E_VM_NOT_FOUND = new VixError(4000);
   public static final VixError VIX_E_SNAPSHOT_EXISTS = new VixError(13004);
   public static final VixError VIX_E_SNAPSHOT_DISKLIB = new VixError(13002);
   public static final VixError VIX_E_CANNOT_CONNECT_TO_HOST = new VixError(18000);
   public static final VixError VIX_E_VM_NOT_RUNNING = new VixError(3006);
   public static final VixError VIX_E_SNAPSHOT_INDEPENDENTDISK = new VixError(13016);
   public static final VixError VIX_E_HOST_SERVER_NOT_FOUND = new VixError(14008);
   public static final VixError VIX_E_DISK_OPENPARENT = new VixError(16012);
   public static final VixError VIX_E_DISK_INVAL = new VixError(16000);
   public static final VixError VIX_E_MUST_BE_CONSOLE_USER = new VixError(3027);
   public static final VixError VIX_E_SNAPSHOT_NAMETOOLONG = new VixError(13012);
   public static final VixError VIX_E_SNAPSHOT_MIN_FREE_SPACE = new VixError(13020);
   public static final VixError VIX_E_TOOLS_INSTALL_GUEST_NOT_READY = new VixError(21007);
   public static final VixError VIX_E_TOOLS_INSTALL_SIG_CHECK_FAILED = new VixError(21008);
   public static final VixError VIX_E_INTERACTIVE_SESSION_NOT_PRESENT = new VixError(3034);
   public static final VixError VIX_E_SNAPSHOT_CONFIG = new VixError(13007);
   public static final VixError VIX_E_DISK_INVALID_CONNECTION = new VixError(16054);
   public static final VixError VIX_E_HOST_FILE_ERROR_EOF = new VixError(14005);
   public static final VixError VIX_E_FILE_ACCESS_ERROR = new VixError(13);
   public static final VixError VIX_E_HOST_NBD_HASHFILE_INIT = new VixError(14013);
   public static final VixError VIX_E_CRYPTO_EMPTY = new VixError(17011);
   public static final VixError VIX_E_SNAPSHOT_NOPERM = new VixError(13006);
   public static final VixError VIX_E_DISK_KEY_NOTFOUND = new VixError(16052);
   public static final VixError VIX_E_SUSPEND_ERROR = new VixError(3012);
   public static final VixError VIX_E_TOOLS_INSTALL_AUTO_NOT_SUPPORTED = new VixError(21006);
   public static final VixError VIX_E_SNAPSHOT_DUPLICATEDDISK = new VixError(13015);
   public static final VixError VIX_E_DISK_FULL = new VixError(8);
   public static final VixError VIX_E_HOST_DISK_INVALID_VALUE = new VixError(14003);
   public static final VixError VIX_E_NO_GUEST_OS_INSTALLED = new VixError(3010);
   public static final VixError VIX_E_INCORRECT_FILE_TYPE = new VixError(9);
   public static final VixError VIX_E_SNAPSHOT_INVAL = new VixError(13000);
   public static final VixError VIX_E_DISK_UNSUPPORTEDDEVICE = new VixError(16066);
   public static final VixError VIX_E_DISK_RAWTOOBIG = new VixError(16024);
   public static final VixError VIX_E_HOST_NBD_HASHFILE_VOLUME = new VixError(14012);
   public static final VixError VIX_E_SNAPSHOT_MAXSNAPSHOTS = new VixError(13019);
   public static final VixError VIX_E_TOO_MANY_HANDLES = new VixError(1002);
   public static final VixError VIX_E_FILE_READ_ONLY = new VixError(11);
   public static final VixError VIX_E_INVALID_ARG = new VixError(3);
   public static final VixError VIX_E_CRYPTO_LOCKED = new VixError(17010);
   public static final VixError VIX_E_DISK_NOTENCRYPTED = new VixError(16016);
   public static final VixError VIX_E_TOOLS_INSTALL_NO_IMAGE = new VixError(21000);
   public static final VixError VIX_E_DISK_NOKEYOVERRIDE = new VixError(16015);
   public static final VixError VIX_E_SNAPSHOT_NOCHANGE = new VixError(13008);
   public static final VixError VIX_E_UNFINISHED_JOB = new VixError(29);
   public static final VixError VIX_E_FAIL = new VixError(1);
   public static final VixError VIX_E_OP_NOT_SUPPORTED_ON_GUEST = new VixError(3003);
   public static final VixError VIX_E_INVALID_XML = new VixError(2002);
   public static final VixError VIX_E_REQUIRES_LARGE_FILES = new VixError(14);
   public static final VixError VIX_E_CANCELLED = new VixError(10);
   public static final VixError VIX_E_CRYPTO_RANDOM_DEVICE = new VixError(17003);
   public static final VixError VIX_E_VM_ALREADY_LOADED = new VixError(4004);
   public static final VixError VIX_E_NOT_SUPPORTED_FOR_VM_VERSION = new VixError(4001);
   public static final VixError VIX_E_TOOLS_INSTALL_IN_PROGRESS = new VixError(21011);
   public static final VixError VIX_E_TOOLS_INSTALL_IMAGE_INACCESIBLE = new VixError(21001);
   public static final VixError VIX_E_SCREEN_CAPTURE_COMPRESSION_FAIL = new VixError(19002);
   public static final VixError VIX_E_DISK_NEEDSREPAIR = new VixError(16006);
   public static final VixError VIX_E_NOT_FOUND = new VixError(2000);
   public static final VixError VIX_E_READ_ONLY_PROPERTY = new VixError(6002);
   public static final VixError VIX_E_SCREEN_CAPTURE_LARGE_DATA = new VixError(19003);
   public static final VixError VIX_E_DISK_TOOMANYREDO = new VixError(16028);
   public static final VixError VIX_E_DISK_NEEDKEY = new VixError(16014);
   public static final VixError VIX_E_HOST_TCP_CONN_LOST = new VixError(14011);
   public static final VixError VIX_E_OBJECT_IS_BUSY = new VixError(5);
   public static final VixError VIX_E_DISK_INVALIDPARTITIONTABLE = new VixError(16018);
   public static final VixError VIX_E_HOST_SOCKET_CREATION_ERROR = new VixError(14007);
   public static final VixError VIX_E_DISK_PARTMISMATCH = new VixError(16010);
   public static final VixError VIX_E_TOOLS_INSTALL_INIT_FAILED = new VixError(21005);
   public static final VixError VIX_E_EMPTY_PASSWORD_NOT_ALLOWED_IN_GUEST = new VixError(3033);
   public static final VixError VIX_E_DISK_NOLICENSE = new VixError(16064);
   public static final VixError VIX_E_GUEST_OPERATIONS_PROHIBITED = new VixError(3017);
   public static final VixError VIX_E_INVALID_MESSAGE_HEADER = new VixError(10000);
   public static final VixError VIX_E_INVALID_SERIALIZED_DATA = new VixError(6004);
   public static final VixError VIX_E_VM_HOST_DISCONNECTED = new VixError(34);
   public static final VixError VIX_E_UNABLE_TO_REPLAY_VM = new VixError(3039);
   public static final VixError VIX_E_DISK_NOKEY = new VixError(16017);
   public static final VixError VIX_E_SNAPSHOT_VIXFILE = new VixError(13013);
   public static final VixError VIX_E_NOT_SUPPORTED_ON_HANDLE_TYPE = new VixError(1001);
   public static final VixError VIX_E_CRYPTO_UNKNOWN_ALGORITHM = new VixError(17000);
   public static final VixError VIX_E_CANNOT_START_READ_ONLY_VM = new VixError(3005);
   public static final VixError VIX_E_INVALID_UTF8_STRING = new VixError(27);
   public static final VixError VIX_E_WRAPPER_WORKSTATION_NOT_INSTALLED = new VixError(22001);
   public static final VixError VIX_E_INTERACTIVE_SESSION_USER_MISMATCH = new VixError(3035);
   public static final VixError VIX_E_CANNOT_AUTHENTICATE_WITH_GUEST = new VixError(3024);
   public static final VixError VIX_E_CRYPTO_ERROR = new VixError(17008);
   public static final VixError VIX_E_CRYPTO_BAS_PASSWORD = new VixError(17005);
   public static final VixError VIX_E_FILE_TOO_BIG = new VixError(21);
   public static final VixError VIX_E_ANON_GUEST_OPERATIONS_PROHIBITED = new VixError(3018);
   public static final VixError VIX_E_NOT_SUPPORTED_ON_REMOTE_OBJECT = new VixError(20);
   public static final VixError VIX_E_SNAPSHOT_DUMPER = new VixError(13001);
   public static final VixError VIX_E_ALREADY_EXISTS = new VixError(23);
   public static final VixError VIX_E_DISK_NODEVICE = new VixError(16065);
   public static final VixError VIX_E_SNAPSHOT_MEMORY_ON_INDEPENDENT_DISK = new VixError(13018);
   public static final VixError VIX_E_NOT_ALLOWED_DURING_VM_RECORDING = new VixError(3029);
   public static final VixError VIX_E_CONSOLE_GUEST_OPERATIONS_PROHIBITED = new VixError(3026);
   public static final VixError VIX_E_NOT_SUPPORTED = new VixError(6);
   public static final VixError VIX_E_OBJECT_NOT_FOUND = new VixError(25);
   public static final VixError VIX_E_WRAPPER_VERSION_NOT_FOUND = new VixError(22002);
   public static final VixError VIX_E_HOST_DISK_SECTORSIZE = new VixError(14004);
   public static final VixError VIX_E_OPERATION_ALREADY_IN_PROGRESS = new VixError(31);
   public static final VixError VIX_E_DISK_NOTNORMAL = new VixError(16019);
   public static final VixError VIX_E_UNRECOGNIZED_PROPERTY = new VixError(6000);
   public static final VixError VIX_E_DISK_TOOMANYOPENFILES = new VixError(16027);
   public static final VixError VIX_E_SNAPSHOT_INCONSISTENT = new VixError(13011);
   public static final VixError VIX_E_VM_IS_RUNNING = new VixError(3007);
   public static final VixError VIX_E_LICENSE = new VixError(32);
   public static final VixError VIX_E_DISK_NOTSUPPORTED = new VixError(16013);
   public static final VixError VIX_E_SNAPSHOT_DISKLOCKED = new VixError(13014);
   public static final VixError VIX_E_SCREEN_CAPTURE_ERROR = new VixError(19000);
   public static final VixError VIX_E_DISK_ENCODING = new VixError(16061);
   public static final VixError VIX_E_HOST_TCP_SOCKET_ERROR = new VixError(14010);
   public static final VixError VIX_E_DISK_CANTREPAIR = new VixError(16062);
   public static final VixError VIX_E_POWEROP_SCRIPTS_NOT_AVAILABLE = new VixError(3009);
   public static final VixError VIX_E_INVALID_MESSAGE_BODY = new VixError(10001);
   public static final VixError VIX_E_HOST_NOT_CONNECTED = new VixError(26);
   public static final VixError VIX_E_SNAPSHOT_LOCKED = new VixError(13010);
   public static final VixError VIX_E_NOT_FOR_REMOTE_HOST = new VixError(18001);
   public static final VixError VIX_E_TOOLS_INSTALL_NO_DEVICE = new VixError(21002);
   public static final VixError VIX_E_SNAPSHOT_VERSION = new VixError(13005);
   public static final VixError VIX_E_VM_INSUFFICIENT_HOST_MEMORY = new VixError(3011);
   public static final VixError VIX_E_VM_NOT_ENOUGH_CPUS = new VixError(3013);
   public static final VixError VIX_E_NO_DISPLAY_SERVER = new VixError(3043);
   public static final VixError VIX_E_DISK_CID_MISMATCH = new VixError(16008);
   public static final VixError VIX_E_BUFFER_TOOSMALL = new VixError(24);
   public static final VixError VIX_E_DISK_INVALIDDISK = new VixError(16063);
   public static final VixError VIX_E_DISK_SUBSYSTEM_INIT_FAIL = new VixError(16053);
   public static final VixError VIX_E_FILE_ALREADY_LOCKED = new VixError(15);
   public static final VixError VIX_E_BAD_VM_INDEX = new VixError(8000);
   public static final VixError VIX_E_MISSING_ANON_GUEST_ACCOUNT = new VixError(3023);
   public static final VixError VIX_E_SNAPSHOT_CHECKPOINT = new VixError(13009);
   public static final VixError VIX_E_DISK_NOIO = new VixError(16002);
   public static final VixError VIX_E_VMDB = new VixError(16);
   public static final VixError VIX_E_NOT_ALLOWED_DURING_VM_REPLAY = new VixError(3030);
   public static final VixError VIX_E_MISSING_REQUIRED_PROPERTY = new VixError(6003);
   public static final VixError VIX_E_HOST_NETBLKDEV_HANDSHAKE = new VixError(14006);
   public static final VixError VIX_E_CRYPTO_INVALID_OPERATION = new VixError(17002);

   public VixError(long val) {
      super(val);
   }

   public VixError() {
      super();
   }
}
