/*******************************************************************************
 * Copyright (c) 2009 VMware, Inc. licensed under the terms of the BSD. All
 * other rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * - Neither the name of VMware, Inc. nor the names of its contributors may be
 * used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

/* Auto-generated by VixHeaderToJava from the vix.h header file */
package com.vmware.vix;

@SuppressWarnings("serial")
public class VixPropertyID extends VixType {

   public static final VixPropertyID VIX_PROPERTY_SNAPSHOT_IS_REPLAYABLE = new VixPropertyID(4207);
   public static final VixPropertyID VIX_PROPERTY_VM_SUPPORTED_FEATURES = new VixPropertyID(197);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_GUEST_PROGRAM_ELAPSED_TIME = new VixPropertyID(3017);
   public static final VixPropertyID VIX_PROPERTY_FOUND_ITEM_LOCATION = new VixPropertyID(4010);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_PROCESS_ID = new VixPropertyID(3051);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_PROCESS_COMMAND = new VixPropertyID(3053);
   public static final VixPropertyID VIX_PROPERTY_VM_IN_VMTEAM = new VixPropertyID(128);
   public static final VixPropertyID VIX_PROPERTY_NONE = new VixPropertyID(0);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_ERROR_CODE = new VixPropertyID(3000);
   public static final VixPropertyID VIX_PROPERTY_SNAPSHOT_POWERSTATE = new VixPropertyID(4205);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_FILE_MOD_TIME = new VixPropertyID(3062);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_FOUND_ITEM_DESCRIPTION = new VixPropertyID(3036);
   public static final VixPropertyID VIX_PROPERTY_VM_IS_RECORDING = new VixPropertyID(236);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_SHARED_FOLDER_FLAGS = new VixPropertyID(3049);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_USER_MESSAGE = new VixPropertyID(3002);
   public static final VixPropertyID VIX_PROPERTY_VM_IS_REPLAYING = new VixPropertyID(237);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_SCREEN_IMAGE_SIZE = new VixPropertyID(3058);
   public static final VixPropertyID VIX_PROPERTY_VM_VMTEAM_PATHNAME = new VixPropertyID(105);
   public static final VixPropertyID VIX_PROPERTY_HOST_API_VERSION = new VixPropertyID(51);
   public static final VixPropertyID VIX_PROPERTY_META_DATA_CONTAINER = new VixPropertyID(2);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_SHARED_FOLDER_COUNT = new VixPropertyID(3046);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_VM_IN_GROUP = new VixPropertyID(3001);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_ITEM_NAME = new VixPropertyID(3035);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_FILE_SIZE = new VixPropertyID(3061);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_VM_VARIABLE_STRING = new VixPropertyID(3056);
   public static final VixPropertyID VIX_PROPERTY_VM_IS_RUNNING = new VixPropertyID(196);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_FILE_FLAGS = new VixPropertyID(3054);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_HANDLE = new VixPropertyID(3010);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_SHARED_FOLDER_HOST = new VixPropertyID(3048);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_COMMAND_OUTPUT = new VixPropertyID(3005);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_PROCESS_BEING_DEBUGGED = new VixPropertyID(3057);
   public static final VixPropertyID VIX_PROPERTY_VM_VMX_PATHNAME = new VixPropertyID(103);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_PROCESS_OWNER = new VixPropertyID(3052);
   public static final VixPropertyID VIX_PROPERTY_VM_MEMORY_SIZE = new VixPropertyID(106);
   public static final VixPropertyID VIX_PROPERTY_VM_NUM_VCPUS = new VixPropertyID(101);
   public static final VixPropertyID VIX_PROPERTY_SNAPSHOT_DESCRIPTION = new VixPropertyID(4201);
   public static final VixPropertyID VIX_PROPERTY_VM_TOOLS_STATE = new VixPropertyID(152);
   public static final VixPropertyID VIX_PROPERTY_HOST_HOSTTYPE = new VixPropertyID(50);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_EXIT_CODE = new VixPropertyID(3004);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_GUEST_OBJECT_EXISTS = new VixPropertyID(3011);
   public static final VixPropertyID VIX_PROPERTY_SNAPSHOT_DISPLAYNAME = new VixPropertyID(4200);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_GUEST_PROGRAM_EXIT_CODE = new VixPropertyID(3018);
   public static final VixPropertyID VIX_PROPERTY_VM_READ_ONLY = new VixPropertyID(107);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_SCREEN_IMAGE_DATA = new VixPropertyID(3059);
   public static final VixPropertyID VIX_PROPERTY_VM_POWER_STATE = new VixPropertyID(129);
   public static final VixPropertyID VIX_PROPERTY_JOB_RESULT_PROCESS_START_TIME = new VixPropertyID(3055);

   public VixPropertyID(long val) {
      super(val);
   }

   public VixPropertyID() {
      super();
   }
}
